defaults:
  run:
    shell: powershell

name: gitea-CI-sparrow-poetry
on:
  push:
#    tags:
#      - "*w*"

jobs:
  poetry-src-regen:
    runs-on: windows-amd64
    env:
      PYTHONIOENCODING: 'utf-8'
      PYTHONUTF8: 1
      GITEA_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      ACTIONS_URL: https://mwtjc.online:14086/
      GITEA_API_URL: https://mwtjc.online:14086/api/v1/
      APP_FOLDER_NAME: 'PySideApp'
    steps:
      - name: 检出repo
        uses: ${{ env.ACTIONS_URL }}actions/checkout@v4

      - name: 取得hash标记符
        uses: ${{ env.ACTIONS_URL }}actions/go-hashfiles@v0.0.1
        id: hash-go
        with:
          patterns: |-
            py312-win.lock
            pyproject.toml

      - name: 环境安装
        run: |
          pdm use 3.12
          pdm install --lockfile=py312-win.lock
          pdm list
          pdm info

      - name: pyui资源更新
        working-directory: ${{ env.APP_FOLDER_NAME }}\scripts
        run: pdm run regen_ui.py

      - name: 构建前测试
        run: pdm run test

      - name: 取得缓存 nuitka
        uses: ${{ env.ACTIONS_URL }}actions/cache/restore@v4
        with:
          path: |
            .\dist
          key: dist-${{ steps.hash-go.outputs.hash }}

      - name: Nuitka构建-本地-单文件
        run: pdm run build

      - name: 缓存 nuitka
        uses: ${{ env.ACTIONS_URL }}actions/cache/save@v4
        with:
          path: |
            .\dist
          key: dist-${{ steps.hash-go.outputs.hash }}

      - name: 压缩7z
        run: 7z.exe a -t7z -m0=LZMA2 -mmt=on -mx9 -mqs=on -bsp2  -mtc=on -mta=on ".\dist7z.7z" ".\dist\${{ env.APP_FOLDER_NAME }}.dist"

      - name: 获取 commit 哈希
        run: |
          # 获取短 commit hash
          $commit = git rev-parse --short HEAD
          # 获取文件大小（以 MB 为单位）
          $size = [math]::Round((Get-Item "output.zip").length / 1MB, 2)
          # 获取构建时间
          BUILD_TIME=$((Get-Date).ToString('yyyyMMddHHmmss'))
          # 构造新文件名
          $newFileName = "Win64_${BUILD_TIME}_${commit}_${size}MB.7z"
          # 重命名文件
          Rename-Item "dist7z.7z" $newFileName

      - name: 上传CI成品
        uses: ${{ env.ACTIONS_URL }}actions/upload-artifact@v3
        with:
          path: |
            ./*.7z
          if-no-files-found: error
          compression-level: 0
          retention-days: 5


